[build]
  base = "/"  # Base directory untuk proyek
  command = "cd frontend && npm run build"
  publish = "frontend/dist"  # Folder build frontend (jika menggunakan React, Vue, dll.)

[functions]
  directory = "backend/netlify-functions"

