[build]
  base = "/"  
  command = "cd frontend && npm ci && npm run build"
  publish = "frontend/dist"  # 

[functions]
  directory = "backend/netlify-functions"

[build.environment]
  NODE_VERSION = "16"  
